# Copyright (c) 2025 Gaia Project
# SPDX-License-Identifier: MIT

ARG REGISTRY=
ARG IMAGE_ARCH=
ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=
ARG BASE_VERSION2=
ARG BASE_IMAGE2=
ARG GPU=

FROM ${BASE_IMAGE}:${BASE_VERSION} AS builder

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
        coreutils \
        procps \
        patchelf \
        python3 \
        python3-pip \
        scons \
        libc-bin \
        binutils \
    && apt-mark minimize-manual -y \
    && apt-get autopurge -y \
    && apt-get clean


# install staticx
RUN pip3 install --break-system-packages setuptools && \
    pip3 install --break-system-packages staticx
