# Copyright (c) 2025 Gaia Project
# SPDX-License-Identifier: MIT

ARG REGISTRY=
ARG IMAGE_ARCH=
ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=
ARG BASE_VERSION2=
ARG BASE_IMAGE2=
ARG GPU=

FROM ${BASE_IMAGE}:${BASE_VERSION} AS builder

RUN apt-get update \
    && apt-get upgrade -y --no-install-recommends \
    && apt-get install -y --no-install-recommends \
        gcc \
        gcc-aarch64-linux-gnu \
        gcc-arm-linux-gnueabihf \
        gcc-riscv64-linux-gnu \
        u-boot-tools \
        libelf-dev \
        bc bison build-essential coccinelle \
        device-tree-compiler dfu-util efitools flex gdisk graphviz imagemagick \
        liblz4-tool libgnutls28-dev libguestfs-tools libncurses-dev \
        libpython3-dev libsdl2-dev libssl-dev lz4 lzma lzma-alone openssl \
        pkg-config python3 python3-asteval python3-coverage python3-filelock \
        python3-pkg-resources python3-pycryptodome python3-pyelftools \
        python3-pytest python3-pytest-xdist python3-sphinxcontrib.apidoc \
        python3-sphinx-rtd-theme python3-subunit python3-testtools \
        python3-virtualenv swig uuid-dev \
        rsync \
        pahole \
    && apt-mark minimize-manual -y \
    && apt-get autopurge -y \
    && apt-get clean

RUN rm /etc/apt/apt.conf.d/docker-clean
RUN rm -rf /tmp/* /var/tmp/
RUN ln -s /tmp /var/tmp

WORKDIR /source

# create the builder user with the same uid/gid
# than the user outside the container
ARG USER_ID=1000
ARG GROUP_ID=1000
RUN groupadd -g ${GROUP_ID} builder \
    && useradd -u ${USER_ID} -g builder -s /bin/bash builder \
    && mkdir -p /home/builder \
    && chown -R builder:builder /home/builder


USER builder


CMD [ \
    "echo", \
    "'docker run --rm -it -v /u-boot-source:/source commontorizon/u-boot-builder make'" \
]
