# Copyright (c) 2023 Matheus Castello
# SPDX-License-Identifier: MIT

ARG REGISTRY=
ARG IMAGE_ARCH=
ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=
ARG BASE_VERSION2=
ARG BASE_IMAGE2=
ARG CROSS_TARGET_ARCH=
ARG KERNEL_ARCH=
ARG CROSS_COMPILER=
ARG GPU=

FROM --platform=linux/${IMAGE_ARCH} \
    ${BASE_REGISTRY}${BASE_IMAGE}:${BASE_VERSION} AS SDK

ARG REGISTRY
ARG IMAGE_ARCH
ARG BASE_REGISTRY
ARG BASE_IMAGE
ARG BASE_VERSION
ARG BASE_VERSION2
ARG BASE_IMAGE2
ARG GPU

ARG CROSS_TARGET_ARCH
ARG KERNEL_ARCH
ARG CROSS_COMPILER

RUN test -n "$CROSS_TARGET_ARCH" || (echo "CROSS_TARGET_ARCH  not set" && false)
RUN test -n "$CROSS_COMPILER" || (echo "CROSS_COMPILER  not set" && false)
RUN test -n "$KERNEL_ARCH" || (echo "KERNEL_ARCH not set" && false)

ENV CROSS_COMPILE=${CROSS_COMPILER}-
ENV PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/lib/${CROSS_COMPILER}/pkgconfig

ENV DEBIAN_FRONTEND="noninteractive"

RUN dpkg --add-architecture ${CROSS_TARGET_ARCH}

RUN apt-get -q -y update \
    && apt-get -q -y install --no-install-recommends \
        ca-certificates \
        gpg \
        wget \
    && apt-get clean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get -q -y update \
    && apt-get -q -y upgrade \
    && apt-get -q -y install --no-install-recommends \
        git \
        openssl \
        wget \
        curl \
        crossbuild-essential-${CROSS_TARGET_ARCH} \
    && apt-get clean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

# make the cross compiler more usable
RUN ln -s /usr/bin/${CROSS_COMPILER}-gcc /usr/bin/${KERNEL_ARCH}-gcc \
    && ln -s /usr/bin/${CROSS_COMPILER}-g++ /usr/bin/${KERNEL_ARCH}-g++
