# Copyright (c) 2025 Gaia Project
# SPDX-License-Identifier: MIT

ARG REGISTRY=
ARG IMAGE_ARCH=
ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=
ARG BASE_VERSION2=
ARG BASE_IMAGE2=
ARG GPU=


FROM ${BASE_IMAGE}:${BASE_VERSION} AS phobos


RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
        curl \
        tar \
        xz-utils \
        qemu-system \
        qemu-utils \
        qemu-system-common \
        isc-dhcp-server \
        screen \
        libtpms0 \
        swtpm \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY ./entry.sh /usr/bin/entry
COPY ./dhcpd.conf /etc/dhcp/dhcpd.conf

RUN chmod +x /usr/bin/entry


ENTRYPOINT [ "entry" ]
