FROM debian:bookworm-backports AS qemu

# hadolint ignore=DL3015
RUN apt-get update && apt-get install -y qemu-user-static && \
    mv /usr/bin/qemu-aarch64-static /usr/bin/qemu-aarch64 && \
    mv /usr/bin/qemu-arm-static /usr/bin/qemu-arm && \
    mv /usr/bin/qemu-ppc64le-static /usr/bin/qemu-ppc64le && \
    mv /usr/bin/qemu-s390x-static /usr/bin/qemu-s390x && \
    mv /usr/bin/qemu-riscv64-static /usr/bin/qemu-riscv64 && \
    mv /usr/bin/qemu-x86_64-static /usr/bin/qemu-x86_64 && \
    apt-get remove -y qemu-user-static

# workaround for 32bit arm on 64bit, we need only the qemu-arm
# hadolint ignore=DL3015
RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y \
    qemu-user-static:i386 && \
    mv /usr/bin/qemu-arm-static /usr/bin/qemu-arm && \
    rm /usr/bin/qemu-*-static

FROM debian:bookworm AS mirror

# hadolint ignore=DL3015
RUN apt-get update && apt-get install -y golang-go musl-dev

COPY main.go /go/src/binfmt/
RUN go build \
    -o binfmt \
    -ldflags "-extldflags '-static'" \
    /go/src/binfmt/main.go

COPY etc/binfmt.d/00_linuxkit.conf etc/binfmt.d/00_linuxkit.conf

# remove the line that match the architecture from the platform
RUN ARCH=$(uname -m) && \
    sed -i "/^:qemu-${ARCH}:/d" /etc/binfmt.d/00_linuxkit.conf && \
    cat /etc/binfmt.d/00_linuxkit.conf

FROM scratch

ENTRYPOINT []

WORKDIR /

COPY --from=qemu usr/bin/qemu-* usr/bin/
COPY --from=mirror /binfmt usr/bin/binfmt
COPY --from=mirror /etc/binfmt.d/00_linuxkit.conf /etc/binfmt.d/00_linuxkit.conf


CMD [ \
    "/usr/bin/binfmt" \
]
