# Copyright (c) 2025 Gaia Project
# SPDX-License-Identifier: MIT

ARG REGISTRY=
ARG IMAGE_ARCH=
ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=
ARG BASE_VERSION2=
ARG BASE_IMAGE2=
ARG GPU=

FROM ${BASE_IMAGE}:${BASE_VERSION} AS builder

RUN apt-get update \
    && apt-get upgrade -y --no-install-recommends \
    && apt-get install -y --no-install-recommends \
        wget \
        xz-utils \
    && apt-get autopurge -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN rm /etc/apt/apt.conf.d/docker-clean && \
    rm -rf /tmp/* /var/tmp/ && \
    ln -s /tmp /var/tmp


# install zig
RUN IMAGE_ARCH=$(arch) && \
    echo "Building for $IMAGE_ARCH" && \
    if [ "$IMAGE_ARCH" = "aarch64" ] ; then \
        ZIG_ARCH=aarch64; \
    elif [ "$IMAGE_ARCH" = "x86_64" ] ; then \
        ZIG_ARCH=x86_64; \
    else \
        echo "Unsupported architecture"; \
        exit 1; \
    fi && \
    wget --progress=dot:giga --no-check-certificate https://ziglang.org/download/0.13.0/zig-linux-${ZIG_ARCH}-0.13.0.tar.xz \
    && tar -xvf zig-linux-${ZIG_ARCH}-0.13.0.tar.xz \
    && mkdir -p /usr/local/zig \
    && mv zig-linux-${ZIG_ARCH}-0.13.0/* /usr/local/zig \
    && rm -rf zig-linux-${ZIG_ARCH}-0.13.0.tar.xz \
    && ln -s /usr/local/zig/zig /usr/bin/zig

WORKDIR /source


COPY entry.sh /usr/bin/entrypoint


ENTRYPOINT [ "/usr/bin/entrypoint" ]


CMD [ \
    "echo", \
    "'docker run --rm -it -v /zig-source-code:/source pergamos/zig-sdk cmd'" \
]
